GET http://localhost:80/api/item?id=99
Accept: application/json

###
#注册接口
POST http://127.0.0.1:8099/register/save
Content-Type: application/form-Data

###
#登录接口
POST http://127.0.0.1:8099/login/do
Content-Type: application/json

{
  "mobile": "13689889899",
  "password": "123456"
}

###
#热播列表
GET http://127.0.0.1:8099/channel/hot?channelId=1
